table Delivery_Partner_Data
	lineageTag: b00a4ab4-a103-428e-b58d-189ccce0e322

	column DeliveryPartnerID
		dataType: int64
		formatString: 0
		lineageTag: a0fb257a-7c6f-4fbf-a604-691d93794dbc
		summarizeBy: none
		sourceColumn: DeliveryPartnerID

		annotation SummarizationSetBy = Automatic

	column PartnerName
		dataType: string
		lineageTag: 17adc4cc-8b5d-4ba4-8e13-242a396bd95e
		summarizeBy: none
		sourceColumn: PartnerName

		annotation SummarizationSetBy = Automatic

	column HomeCity
		dataType: string
		lineageTag: b4b4dcae-96bc-4f32-8a90-ed3bac660dec
		summarizeBy: none
		sourceColumn: HomeCity

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 232e224c-0442-4080-be22-e846f1a969b0
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column VehicleType
		dataType: string
		lineageTag: aab30769-357d-4f59-ade8-0331d022df65
		summarizeBy: none
		sourceColumn: VehicleType

		annotation SummarizationSetBy = Automatic

	column Rating
		dataType: double
		lineageTag: b2214595-9cae-4c42-be46-2bebb24087a4
		summarizeBy: none
		sourceColumn: Rating

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ExperienceYears
		dataType: int64
		formatString: 0
		lineageTag: dcfe034e-8d75-4a26-ab16-ba13324d5413
		summarizeBy: none
		sourceColumn: ExperienceYears

		annotation SummarizationSetBy = Automatic

	partition Delivery_Partner_Data = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Hello\Downloads\project\BoatSalesProject\data\raw\Delivery_Partner_Data.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DeliveryPartnerID", Int64.Type}, {"PartnerName", type text}, {"HomeCity", type text}, {"Region", type text}, {"VehicleType", type text}, {"Rating", type number}, {"ExperienceYears", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

