table Product_Details
	lineageTag: fe22ef3f-5fa0-4409-9e81-b18af3a7ca67

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: e9877e50-db88-454e-882f-b4b491eefe19
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: fd36fe46-bf9f-4a04-a62b-b8375d984713
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 706ee966-36ac-4370-b17a-a7a0d657323e
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column SubCategory
		dataType: string
		lineageTag: 77d80d83-0ab1-48a8-9bf0-1c198f048df9
		summarizeBy: none
		sourceColumn: SubCategory

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: 083749dd-4f99-4e1a-b1c2-bc093d2d6850
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column HeroFlag
		dataType: int64
		formatString: 0
		lineageTag: b3a0efae-4fa9-4799-b240-00667d1d4fca
		summarizeBy: none
		sourceColumn: HeroFlag

		annotation SummarizationSetBy = Automatic

	column LaunchYear
		dataType: int64
		formatString: 0
		lineageTag: 0d17d310-def5-49d2-b62e-7d16be90550e
		summarizeBy: none
		sourceColumn: LaunchYear

		annotation SummarizationSetBy = Automatic

	column MRP
		dataType: int64
		formatString: 0
		lineageTag: 1328d314-6575-4d79-b964-ae90cbfee646
		summarizeBy: none
		sourceColumn: MRP

		annotation SummarizationSetBy = Automatic

	column CostPrice
		dataType: double
		lineageTag: 83f675cf-0d45-4336-a47c-1ed216017db2
		summarizeBy: none
		sourceColumn: CostPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PopularityWeight
		dataType: double
		lineageTag: e77dfe53-92a7-48f6-bb24-c6f58de8ce03
		summarizeBy: none
		sourceColumn: PopularityWeight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DemandCluster
		dataType: string
		lineageTag: 871589ee-d698-4dd7-bcda-e6d6a86f8c6a
		summarizeBy: none
		sourceColumn: DemandCluster

		annotation SummarizationSetBy = Automatic

	partition Product_Details = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Hello\Downloads\project\BoatSalesProject\data\raw\Product_Details.csv"),[Delimiter=",", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductID", Int64.Type}, {"Brand", type text}, {"Category", type text}, {"SubCategory", type text}, {"ProductName", type text}, {"HeroFlag", Int64.Type}, {"LaunchYear", Int64.Type}, {"MRP", Int64.Type}, {"CostPrice", type number}, {"PopularityWeight", type number}, {"DemandCluster", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

